name: Snapshot - 4.32 Eclipse STS Distribution Build

concurrency:
  group: e432-snapshot
  cancel-in-progress: true

on:
  workflow_run:
    workflows: ["Snapshot - Eclipse LS Extensions"]
    types: [completed]
    branches:
      - "main"
#  workflow_dispatch:

jobs:
  e432-distro:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/gh-hosted-eclipse-distro-build.yml
    with:
      eclipse_profile: 'e432'
      build_type: 'snapshot'
    secrets: inherit